stages:
  - build
  - test

variables:
  DOCKER_COMPOSE_ID: "${CI_PIPELINE_ID}_${CI_JOB_ID}"
cache:
  key: "$CI_PIPELINE_ID"
  paths:
  - node_modules

npm_build:
  stage: build
  script: ci/npm install
  tags:
    - docker

japa:
  stage: test
  script: ci/npm run test
  tags:
    - docker